/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}", // si usas la carpeta /app
  ],
  theme: {
    extend: {
      colors: {
        background: '#edf2f7',
        foreground: '#2d3748',
        card: '#ffffff',
        cardForeground: '#2d3748',
        popover: '#ffffff',
        popoverForeground: '#2d3748',
        primary: '#3182ce',
        primaryForeground: '#ffffff',
        secondary: '#e2e8f0',
        secondaryForeground: '#2d3748',
        muted: '#f7fafc',
        mutedForeground: '#718096',
        accent: '#48bb78',
        accentForeground: '#ffffff',
        destructive: '#f56565',
        destructiveForeground: '#ffffff',
        border: '#cbd5e0',
        input: 'transparent',
        inputBackground: '#ffffff',
        switchBackground: '#cbd5e0',
        ring: '#3182ce',
        chart1: '#3182ce',
        chart2: '#48bb78',
        chart3: '#ed8936',
        chart4: '#9f7aea',
        chart5: '#ecc94b',
        sidebar: '#2c3e4f',
        sidebarForeground: '#e2e8f0',
        sidebarPrimary: '#3182ce',
        sidebarPrimaryForeground: '#ffffff',
        sidebarAccent: '#374151',
        sidebarAccentForeground: '#f3f4f6',
        sidebarBorder: '#374151',
        sidebarRing: '#3182ce',
        success: '#48bb78',
        successForeground: '#ffffff',
        warning: '#ed8936',
        warningForeground: '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.625rem', // equivale a --radius
      },
      fontWeight: {
        normal: '400',
        medium: '500',
      },
    },
  },
  plugins: [],
}